#!/bin/bash

# add just the column headers to the output
gzcat source_data/20020101.csv.gz | head -1 | gzip > wind_data.csv.gz

# add all of the data, skipping the column headers
gzcat source_data/*.gz | grep -v DATE | gzip >> wind_data.csv.gz
